### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by matbesancon** [coin-or/MibS#66]
When installing on OSX:
```shell
./coin.install.sh build --no-prompt --main-proj=MibS CC=gcc-5 CXX=g++-5
./coin.install.sh: line 920: declare: -A: invalid option
```

Same error appears when running just `./coin.install.sh` or `./coin.install.sh fetch build --no-prompt --main-proj=MibS`

**Comment by tkralphs** [comment]
This is because OS X ships with an out-of-date version of bash. If you install a recent version with homebrew, everything should work fine. By the way, I will update the README shortly to indicate that the install script has now migrated to its own repository: https://github.com/coin-or/coinbrew. The new script will work if used in the same way as the old one, but I have also implemented some enhancements.
