### ISSUE TITLE
Confusion about example instance

### ISSUE THREAD

**Issue by barguel** [coin-or/MibS#69]
I am trying to understand the data file format for specifying the lower level problem.

When I look at example milp_10_20_50_2310.txt, I see that the first LR entry is row 0. However, row 0 is the objective for the HPR. So how does MibS interpret row 0 as a constraint in the lower level problem?

**Comment by SaTahernejad** [comment]
This instance has 10 constraints and all of them are lower-level constraints. To make the aux file, the constraints are indexed 0 to 9 and "LR 0" shows that the first lower-level constraint is "R0000000".

**Comment by barguel** [comment]
Okay, so for the purposes of indexing the aux file constraints, MibS will disregard any constraints with an 'N' in the first column? Is that right?

**Comment by SaTahernejad** [comment]
Yes. It is interpreted as the upper-level objective.

**Comment by tkralphs** [comment]
It's not really MibS that is disregarding the objective rows. The problem is being read by an MPS parser, which is independent of MibS. The parser indexes the constraints from 0. This format is a bit fragile, since it depends on the parser actually indexing the constraints in the same order as they are in the MPS file. For this reason, we have extended the format to accept the constraint names in the auxiliary file. This is a better way to do it. but we haven't yet converted the examples.

**Comment by barguel** [comment]
That makes perfect sense. Thanks for the info!
